---
abstract: 'Subclass of Log::Dispatch::Config that observes the start and the end of functions'
author:
  - 'keroyon <keroyon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-Config-Watcher
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DateTime: 0
  DateTime::Duration: 0
  DateTime::Format::Duration: 0
  DateTime::Format::Strptime: 0
  DateTime::HiRes: 0
  Hook::LexWrap: 0
  Log::Dispatch::Config: 0
resources:
  homepage: http://github.com/keroyonn/p5-Log-Dispatch-Config-Watcher/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/keroyonn/p5-Log-Dispatch-Config-Watcher.git
version: 0.01_2
